-- ---------------------------------------------------------------------
-- Услуги из старого каталога (перенос в БД). Применять после db/migrate_services.sql.
-- ---------------------------------------------------------------------
SET NAMES utf8mb4;

-- Разработка сайтов
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'website-development', 'service', 'Разработка сайтов', 'Лендинги, корпоративные сайты и интернет-магазины с фокусом на продажи.', '<p>Создаю сайты, которые не просто красиво выглядят, а приводят клиентов: прорабатываю структуру, тексты и офферы под вашу аудиторию. Мобильная версия, скорость загрузки и SEO — в базовой комплектации.</p><h3>Что входит</h3><ul><li>Лендинги и корпоративные сайты</li><li>Интернет-магазины</li><li>Адаптив под все устройства</li><li>SEO-готовая структура и метаданные</li><li>Интеграция с CRM и аналитикой</li><li>Быстрый запуск — от 2 недель</li></ul><h3>Частые вопросы</h3><p><strong>Сколько стоит разработка сайта?</strong><br>Стоимость зависит от задачи: лендинг — от 40 000 ₽, корпоративный сайт — от 80 000 ₽, интернет-магазин — от 150 000 ₽. Точную смету даю после короткого брифа.</p><p><strong>Сколько времени занимает разработка?</strong><br>Лендинг — 2–3 недели, корпоративный сайт — 3–6 недель. Сроки фиксируем в договоре и придерживаемся их.</p>', 40000, 'from', NULL, '🌐', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 100, 'Разработка сайтов', 'Лендинги, корпоративные сайты и интернет-магазины с фокусом на продажи.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'website-development');

-- Сопровождение и поддержка сайтов
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'website-support', 'service', 'Сопровождение и поддержка сайтов', 'Абонентское обслуживание: обновления, доработки, мониторинг и защита.', '<p>Беру сайт на абонентское обслуживание: слежу за доступностью, обновляю CMS и плагины, оперативно вношу правки, резервирую данные. Вы занимаетесь бизнесом, а сайт работает без сюрпризов.</p><h3>Что входит</h3><ul><li>Мониторинг доступности 24/7</li><li>Обновления CMS, плагинов и безопасности</li><li>Внесение правок и небольших доработок</li><li>Резервное копирование и восстановление</li><li>Защита от взломов и спама</li><li>Отчётность о проделанной работе</li></ul><h3>Частые вопросы</h3><p><strong>Что входит в абонентское обслуживание?</strong><br>Базовая поддержка — мониторинг, обновления, резервные копии и до 2–4 часов правок в месяц. Состав и объём фиксируем в тарифе.</p><p><strong>Можно ли заказать разовую поддержку?</strong><br>Да, разовые работы — обновление, чистка от вирусов, мелкие доработки — тоже возможны, с фиксацией объёма и стоимости.</p>', 5000, 'from', 'в месяц', '🛠️', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 110, 'Сопровождение и поддержка сайтов', 'Абонентское обслуживание: обновления, доработки, мониторинг и защита.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'website-support');

-- CRM-системы
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'crm-systems', 'service', 'CRM-системы', 'Внедрение, доработка и интеграция CRM: все заявки и продажи в одном месте.', '<p>Помогаю выбрать и внедрить CRM под ваш процесс продаж: настраиваю воронку, автоматизирую рутину, подключаю телефонию, почту и мессенджеры. Продажи перестают теряться.</p><h3>Что входит</h3><ul><li>Внедрение с нуля или переход с другой CRM</li><li>Настройка воронки продаж и этапов</li><li>Интеграции: сайт, телефония, почта, мессенджеры</li><li>Автоматизация рутинных действий</li><li>Отчёты для руководителя</li><li>Обучение сотрудников</li></ul><h3>Частые вопросы</h3><p><strong>Какую CRM выбрать?</strong><br>Обычно рекомендую amoCRM, Bitrix24 или 1С:CRM в зависимости от масштаба и бюджета. На старте провожу аудит процессов и подбираю оптимальный вариант.</p>', 60000, 'from', NULL, '🤝', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 120, 'CRM-системы', 'Внедрение, доработка и интеграция CRM: все заявки и продажи в одном месте.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'crm-systems');

-- Базы данных
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'databases', 'service', 'Базы данных', 'Проектирование, оптимизация, миграция и администрирование БД.', '<p>Проектирую схемы данных, оптимизирую медленные запросы, переношу данные между системами и администрирую СУБД. База становится быстрой и надёжной, а не «узким местом».</p><h3>Что входит</h3><ul><li>Проектирование схем данных</li><li>Оптимизация запросов и индексов</li><li>Миграция данных между СУБД</li><li>Резервное копирование и восстановление</li><li>Администрирование MySQL, PostgreSQL</li><li>Аудит производительности</li></ul><h3>Частые вопросы</h3><p><strong>Какие СУБД поддерживаете?</strong><br>Основные: MySQL, MariaDB, PostgreSQL. Также работаю с MS SQL и разбираюсь с проблемами миграций между ними.</p>', 30000, 'from', NULL, '🗄️', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 130, 'Базы данных', 'Проектирование, оптимизация, миграция и администрирование БД.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'databases');

-- Корпоративный софт
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'corporate-software', 'service', 'Корпоративный софт', 'Внутренние системы и автоматизация бизнес-процессов компании.', '<p>Разрабатываю внутренние системы, которые убирают ручной труд: порталы, складской учёт, документооборот, интеграции между отделами. Процессы становятся прозрачными и управляемыми.</p><h3>Что входит</h3><ul><li>Внутренние порталы и кабинеты</li><li>Учёт и складские системы</li><li>Автоматизация бизнес-процессов</li><li>Интеграция с 1С, CRM и телефонией</li><li>Личные кабинеты клиентов</li><li>Поэтапное внедрение с обучением</li></ul><h3>Частые вопросы</h3><p><strong>С чего начинается разработка корпоративного софта?</strong><br>С аудита процессов: определяем, что автоматизировать в первую очередь, считаем эффект и только потом проектируем систему. Так вы получаете результат быстро и без лишних затрат.</p>', NULL, 'none', 'по запросу', '💻', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 140, 'Корпоративный софт', 'Внутренние системы и автоматизация бизнес-процессов компании.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'corporate-software');

-- Интеграция AI/LLM
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'ai-integration', 'service', 'Интеграция AI/LLM', 'Чат-боты и обработка обращений на базе нейросетей.', '<p>Подключаю AI к вашему бизнесу: умные чат-боты на сайт, автоматическая обработка заявок и типовых вопросов, генерация ответов для менеджеров. Клиенты получают ответы мгновенно, вы экономите время.</p><h3>Что входит</h3><ul><li>Чат-боты на базе GPT/LLM</li><li>Автоматизация обработки обращений</li><li>Интеграция AI с CRM и базами знаний</li><li>Голосовые ассистенты</li><li>Помощник для менеджеров по продажам</li><li>Пилотный запуск на реальных данных</li></ul><h3>Частые вопросы</h3><p><strong>Насколько это дорого и сложно?</strong><br>Современные LLM-сервисы стоят копейки за запрос. Сложность — в настройке под вашу специфику, и это как раз моя работа: от демо-бота до полноценной интеграции.</p>', 50000, 'from', NULL, '✨', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 150, 'Интеграция AI/LLM', 'Чат-боты и обработка обращений на базе нейросетей.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'ai-integration');

-- Интеграции и API
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'api-integrations', 'service', 'Интеграции и API', 'Связываю 1С, телефонию, мессенджеры и маркетплейсы в единую систему.', '<p>Объединяю разрозненные сервисы: 1С, телефония, мессенджеры, маркетплейсы, платёжные системы. Данные перестают дублироваться, операции ускоряются, отчёты сходятся.</p><h3>Что входит</h3><ul><li>Интеграция с 1С, телефонией, маркетплейсами</li><li>Обмен данными между сервисами</li><li>Платёжные системы и онлайн-кассы</li><li>Вебхуки и API-мосты</li><li>Автоматическая синхронизация остатков и заказов</li><li>Документирование интеграций</li></ul><h3>Частые вопросы</h3><p><strong>Какие интеграции самые частые?</strong><br>Сайт → CRM, CRM → 1С, маркетплейсы → склад, телефония → CRM. Но решаем любые задачи обмена данными между системами.</p>', 25000, 'from', NULL, '🔗', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 160, 'Интеграции и API', 'Связываю 1С, телефонию, мессенджеры и маркетплейсы в единую систему.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'api-integrations');

-- Telegram/WhatsApp-интеграции
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'messenger-integrations', 'service', 'Telegram/WhatsApp-интеграции', 'Подключаю мессенджеры к отделу продаж: заявки, переписки, рассылки.', '<p>Настраиваю приём заявок и переписку с клиентами прямо в Telegram и WhatsApp: интеграция с сайтом и CRM, уведомления менеджерам, автоответы, рассылки. Продажи едут за клиентом.</p><h3>Что входит</h3><ul><li>Кнопки и виджеты мессенджеров на сайте</li><li>Приём заявок из Telegram/WhatsApp в CRM</li><li>Уведомления менеджерам о новых сообщениях</li><li>Автоответы и сценарии</li><li>Рассылки по базе клиентов</li><li>Интеграция с телефонией</li></ul><h3>Частые вопросы</h3><p><strong>Работает ли это с обычным номером без API?</strong><br>Для полноценной автоматизации нужен доступ к API (Telegram Bot или WhatsApp Business API). Помогаю настроить и пройти верификацию.</p>', 20000, 'from', NULL, '💬', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 170, 'Telegram/WhatsApp-интеграции', 'Подключаю мессенджеры к отделу продаж: заявки, переписки, рассылки.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'messenger-integrations');

-- Аудит и ускорение сайтов
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'website-speed', 'service', 'Аудит и ускорение сайтов', 'Аудит Core Web Vitals и ускорение загрузки до лидеров ниши.', '<p>Провожу технический аудит и ускоряю сайт: оптимизирую картинки, код, кеширование и хостинг. Быстрый сайт — это больше заявок и выше позиции в поиске.</p><h3>Что входит</h3><ul><li>Аудит Core Web Vitals и PageSpeed</li><li>Оптимизация изображений (WebP/AVIF)</li><li>Кеширование и сжатие</li><li>Оптимизация кода и скриптов</li><li>Ускорение хостинга и CDN</li><li>Контрольный замер после работ</li></ul><h3>Частые вопросы</h3><p><strong>Что такое Core Web Vitals?</strong><br>Это метрики скорости и удобства, которые Google учитывает в ранжировании: скорость загрузки, отзывчивость и стабильность вёрстки. Привожу их в зелёную зону.</p>', 15000, 'from', NULL, '⚡', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 180, 'Аудит и ускорение сайтов', 'Аудит Core Web Vitals и ускорение загрузки до лидеров ниши.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'website-speed');

-- Автоматизация документооборота / RPA
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'rpa-document', 'service', 'Автоматизация документооборота / RPA', 'Роботы, которые заполняют документы и выполняют рутину за сотрудников.', '<p>Автоматизирую рутинные операции: заполнение документов, перенос данных между системами, обработку вложений почты. Сотрудники перестают заниматься «копипастой», роботы делают это за них.</p><h3>Что входит</h3><ul><li>Автоматизация ввода и переноса данных</li><li>Заполнение и проверка документов</li><li>Обработка входящей почты и вложений</li><li>Интеграция с учётными системами</li><li>Контроль ошибок и логирование</li><li>Оценка эффекта до автоматизации</li></ul><h3>Частые вопросы</h3><p><strong>Что такое RPA простыми словами?</strong><br>RPA — это программные роботы, которые повторяют действия человека в программах: копируют, вставляют, заполняют. Это убирает рутину без замены учётных систем.</p>', NULL, 'none', 'по запросу', '🤖', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 190, 'Автоматизация документооборота / RPA', 'Роботы, которые заполняют документы и выполняют рутину за сотрудников.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'rpa-document');

-- AI-ассистенты для бизнеса
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, booking_enabled, shop_enabled, comments_enabled, rating_enabled, postpay, payment_methods, template_id, active, sort_order, meta_title, meta_description)
SELECT 'ai-assistants', 'service', 'AI-ассистенты для бизнеса', 'Персональные AI-помощники для продаж, поддержки и внутренних процессов.', '<p>Создаю AI-ассистентов, которые работают в вашей команде: отвечают клиентам, готовят коммерческие предложения, анализируют обращения, помогают менеджерам. Это как дополнительный сотрудник без зарплаты.</p><h3>Что входит</h3><ul><li>Ассистент отдела продаж</li><li>AI-поддержка клиентов 24/7</li><li>Генерация КП, писем и контента</li><li>Анализ обращений и настроений</li><li>Интеграция с CRM и мессенджерами</li><li>Обучение на ваших данных</li></ul><h3>Частые вопросы</h3><p><strong>AI будет выдавать неточности?</strong><br>Качество зависит от настройки: ограничиваю модель вашей базой знаний, добавляю проверки и человека в цикле для ответственных операций. Результат контролируем.</p>', 60000, 'from', NULL, '🧠', 'piece', 60, 0, 0, 1, 1, 1, '["cash","card","transfer","sbp"]', (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 200, 'AI-ассистенты для бизнеса', 'Персональные AI-помощники для продаж, поддержки и внутренних процессов.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'ai-assistants');
