-- ---------------------------------------------------------------------
-- Тестовые услуги для проверки модуля «Запись» (брони по дате и времени).
-- Применять после db/migrate_services.sql и db/migrate_bookings.sql.
-- Все услуги с booking_enabled = 1, разными длительностями, буферами,
-- подтверждением (авто/ручное) и способами оплаты.
-- ---------------------------------------------------------------------
SET NAMES utf8mb4;

-- 1. Бесплатная консультация: авто-подтверждение, постоплата, без буферов
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, buffer_before_min, buffer_after_min, booking_enabled, auto_confirm, prepay, postpay, payment_methods, category_id, template_id, active, sort_order, meta_title, meta_description)
SELECT 'consultation-project', 'service', 'Консультация по проекту', '30 минут: разберём задачу и наметим план — бесплатно.', '<p>Короткая встреча, на которой разбираем вашу задачу: что нужно сделать, какие есть варианты и сколько это займёт. Подходит, если вы ещё выбираете подрядчика или не уверены в решении.</p><h3>Что обсудим</h3><ul><li>Цель и сроки проекта</li><li>Варианты решения и бюджет</li><li>Что можно сделать своими силами</li><li>Дальнейшие шаги</li></ul>', NULL, 'none', 'бесплатно', NULL, 'time', 30, 0, 0, 1, 1, 0, 1, '["transfer"]', (SELECT id FROM service_categories WHERE slug = 'sajty-i-razrabotka'), (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 100, 'Консультация по проекту', 'Бесплатная консультация 30 минут: разберём задачу и наметим план.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'consultation-project');

-- 2. Вводная встреча по сайту: ручное подтверждение, предоплата, буферы 15/15
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, buffer_before_min, buffer_after_min, booking_enabled, auto_confirm, prepay, postpay, payment_methods, category_id, template_id, active, sort_order, meta_title, meta_description)
SELECT 'website-meeting', 'service', 'Вводная встреча по сайту', '60 минут: бриф, структура и предварительная смета по сайту.', '<p>Подробная встреча по вашему будущему сайту: собираю требования, показываю примеры, вместе намечаем структуру и функции. По итогам присылаю краткое резюме и смету.</p><h3>Что входит</h3><ul><li>Бриф и анализ конкурентов</li><li>Структура страниц и прототип</li><li>Предварительная смета и сроки</li></ul><p>Запись подтверждаю вручную: проверю расписание и пришлю подтверждение.</p>', 2000, 'from', 'за встречу', NULL, 'time', 60, 15, 15, 1, 0, 1, 1, '["card","sbp"]', (SELECT id FROM service_categories WHERE slug = 'sajty-i-razrabotka'), (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 110, 'Вводная встреча по сайту', '60 минут: бриф, структура и предварительная смета по сайту.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'website-meeting');

-- 3. Экспресс-аудит сайта: авто-подтверждение, предоплата, буферы 10/10
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, buffer_before_min, buffer_after_min, booking_enabled, auto_confirm, prepay, postpay, payment_methods, category_id, template_id, active, sort_order, meta_title, meta_description)
SELECT 'site-audit-express', 'service', 'Экспресс-аудит сайта', '45 минут: смотрим сайт вместе и находим, что мешает заявкам.', '<p>Разбираем ваш сайт по чек-листу: скорость, мобильная версия, формы, SEO-база. Показываю проблемы и что исправить в первую очередь.</p><h3>Что проверим</h3><ul><li>Скорость и Core Web Vitals</li><li>Мобильную версию</li><li>Формы и путь клиента</li><li>Базовое SEO</li></ul><p>Оплата при подтверждении записи — переведу ссылку на оплату.</p>', 5000, 'none', 'за аудит', NULL, 'time', 45, 10, 10, 1, 1, 1, 0, '["card","sbp","transfer"]', (SELECT id FROM service_categories WHERE slug = 'audit-i-uskorenie'), (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 120, 'Экспресс-аудит сайта', '45 минут: смотрим сайт вместе и находим, что мешает заявкам.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'site-audit-express');

-- 4. Сессия по CRM: ручное подтверждение, постоплата, буферы 15/15, 90 минут
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, buffer_before_min, buffer_after_min, booking_enabled, auto_confirm, prepay, postpay, payment_methods, category_id, template_id, active, sort_order, meta_title, meta_description)
SELECT 'crm-session', 'service', 'Сессия по CRM', '90 минут: настраиваем воронку и автоматизацию вместе с вами.', '<p>Рабочая сессия по вашей CRM: настраиваем воронку, этапы, поля и автоматизации. Вы смотрите и повторяете, я подсказываю — так настройка остаётся у вас, а не в инструкции.</p><h3>Что успеваем</h3><ul><li>Воронка и этапы продаж</li><li>Автоматизации и напоминания</li><li>Интеграции (сайт, почта, мессенджеры)</li></ul><p>Запись подтверждаю вручную, оплата после сессии.</p>', 6000, 'from', 'за сессию', NULL, 'time', 90, 15, 15, 1, 0, 0, 1, '["cash","card","transfer"]', (SELECT id FROM service_categories WHERE slug = 'crm-i-avtomatizaciya'), (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 130, 'Сессия по CRM', '90 минут: настраиваем воронку и автоматизацию вместе с вами.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'crm-session');

-- 5. Плановая встреча по сопровождению: авто-подтверждение, короткая, буферы 5/5
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, buffer_before_min, buffer_after_min, booking_enabled, auto_confirm, prepay, postpay, payment_methods, category_id, template_id, active, sort_order, meta_title, meta_description)
SELECT 'support-meeting', 'service', 'Плановая встреча по сопровождению', '30 минут: статус работ по сайту и план на следующий период.', '<p>Регулярная встреча для клиентов на сопровождении: что сделано, что в работе, что мешает. Коротко и по делу.</p><h3>Повестка</h3><ul><li>Отчёт по задачам</li><li>План на период</li><li>Вопросы и приоритеты</li></ul>', 1500, 'none', 'за встречу', NULL, 'time', 30, 5, 5, 1, 1, 0, 1, '["card","sbp"]', (SELECT id FROM service_categories WHERE slug = 'soprovozhdenie'), (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 1, 140, 'Плановая встреча по сопровождению', '30 минут: статус работ по сайту и план на следующий период.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'support-meeting');

-- 6. Обучение работе с сайтом: авто-подтверждение, предоплата, буфер после 15, адрес
INSERT INTO services (slug, kind, title, short_description, full_description, price, price_prefix, price_note, icon, unit, duration_min, buffer_before_min, buffer_after_min, booking_enabled, auto_confirm, prepay, postpay, payment_methods, category_id, template_id, address, active, sort_order, meta_title, meta_description)
SELECT 'site-training', 'service', 'Обучение работе с сайтом', '60 минут: научу редактировать страницы, товары и заявки.', '<p>Практическое занятие для вас или сотрудника: как добавлять страницы, менять тексты и фото, обрабатывать заявки и смотреть статистику. Можно очно в Краснодаре или онлайн.</p><h3>Чему научитесь</h3><ul><li>Редактировать страницы и блоки</li><li>Добавлять услуги и товары</li><li>Обрабатывать заявки и письма</li><li>Смотреть отчёты и статистику</li></ul>', 3000, 'none', 'за занятие', NULL, 'time', 60, 0, 15, 1, 1, 1, 0, '["card","sbp","cash"]', (SELECT id FROM service_categories WHERE slug = 'sajty-i-razrabotka'), (SELECT id FROM card_templates WHERE kind = 'service' ORDER BY id LIMIT 1), 'Краснодар, ул. Красная, 176', 1, 150, 'Обучение работе с сайтом', '60 минут: научу редактировать страницы, товары и заявки.'
WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'site-training');
